crud-from-scratch-week6/config/routes.rb
Rails.application.routes.draw do
 resources :statuses do
   member do
     post 'upvote'
   end
 end
   root 'statuses#index'

end

crud-from-scratch-week6/app/models/like.rb
class Like < ActiveRecord::Base

belongs_to :status
end

crud-from-scratch-week6/app/models/status.rb
class Status <ActiveRecord::Base

has_many :likes
  validates :message, :user, presence: true

end

crud-from-scratch-week6/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

crud-from-scratch-week6/app/controllers/likes_controller.rb
class LikesController <ApplicationController

  def upvote
    @status = Status.find(params[:id])
    @status.likes.create
    redirect_to(likes_path)
  end

end

crud-from-scratch-week6/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  def index
    @status = Status.all

  end

  def new
    @status = Status.new

  end

  def create
    @status = Status.new(status_params)


    if @status.save

      redirect_to root_path, notice: 'Status was successfully created.'
    else
      render :new
    end
  end

  def show
    @status = Status.find(params[:id])
  end

  def edit
    @status = Status.find(params[:id])
  end

  def destroy
    @status = Status.find(params[:id])
   if @status.destroy
     redirect_to root_path, notice: 'Status successfully deleted.'
    end
  end

  def update
    @status = Status.find(params[:id])
      if @status.update(status_params)
          redirect_to root_path, notice: 'Status was successfully updated.'
        else
          render :edit
      end
  end

  def upvote
    @status = Status.find(params[:id])
    @status.likes.create
    redirect_to root_path
  end

  private
  def set_status
    @status = Status.find(params[:id])
  end

  def status_params
    params.require(:status).permit(:message, :user)
  end


end

crud-from-scratch-week6/app/helpers/application_helper.rb
module ApplicationHelper
end

crud-from-scratch-week6/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrudFromScratchWeek6</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if notice %>
  <div class="container">
    <div class="alert alert-success"><center><%= notice %></center></div>
    <% end %>


<%= yield %>

</body>
</html>

crud-from-scratch-week6/app/views/statuses/_form.html.erb
<%= form_for(@status, html: {class:"form-horizontal"}) do |f| %>


<div class="form-group">
  <div class="field">
    <div class="control-label col-md-2">
      <%= f.label :message %>
    </div>
  </div>
  <div class="control-label col-md-2">
    <%= f.text_field :message %>
  </div>
</div>

<div class="form-group">
  <div class="field">
    <div class="control-label col-md-2">
      <%= f.label :user %>
    </div>
  </div>
  <div class="control-label col-md-2">
    <%= f.text_field :user %>
  </div>
</div>


<div class="form-group">
  <div class="col-md-4 col-md-offset-2">
    <div class="action">
      <%= f.submit class: "btn btn-primary btn-md active" %>
      <%= f.button link_to('Cancel', root_path), class: "btn btn-default btn-md active" %>
    </div>
  </div>
</div>
<% end %>

crud-from-scratch-week6/app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<ol class="breadcrumb">
  <li><a href="/statuses">Statuses</a></li>
  <li> <%= link_to @status.message, status_path(@status) %></li>
  <li class="active"><%= @status.message %></li>
</ol>
<%= render 'form' %>

crud-from-scratch-week6/app/views/statuses/index.html.erb
<div class="page-header">

<h1>Status Updates</h1>
</div>
<table class="table table-striped table-hover">
  <a class="btn btn-info" <%= link_to 'New Status', new_status_path %></a>


<thead>
   <tr>
     <th>Message</th>
     <th>User</th>
     <th>Likes</th>

   </tr>
 </thead>

 <tbody>
   <% @status.each do |status| %>
     <tr>
       <td><%= link_to "#{status.message}", status %></td>
      <td><%= status.user %></td>
      <td><%= button_to 'Like', upvote_status_path(status), method: :post %>
      <%= pluralize(status.likes.count, "Like") %></td>
      </tr>

   <% end %>


 </tbody>
 </table>

crud-from-scratch-week6/app/views/statuses/new.html.erb
<div class="container">
<%= render 'form' %>
</div>

crud-from-scratch-week6/app/views/statuses/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <a class="btn btn-info" href="/statuses/<%= @status.id %>/edit">Edit</a>
    <%= link_to 'Delete', @status, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

  </div>
  <h1> <%= @status.message %></h1>
</div>

<p>
  <ol class="breadcrumb">
    <li><a href="/statuses">Statuses</a></li>
    <li class="active"><%= @status.message %></li>
  </ol>

</p>